export const testimonials = [
    {
        id: 1,
        image: "https://www.course-api.com/images/people/person-1.jpeg",
        name: "maria ferguson",
        title: "office manager",
        quote: "Fingerstache umami squid, kinfolk subway tile selvage tumblr man braid viral kombucha gentrify fanny pack raclette pok pok mustache.",
        rating: 5,
    },
    {
        id: 2,
        image: "https://www.course-api.com/images/people/person-4.jpeg",
        name: "john doe",
        title: "regular guy",
        quote: "Gastropub sustainable tousled prism occupy. Viral XOXO roof party brunch actually, chambray listicle microdosing put a bird on it paleo subway tile squid umami.",
        rating: 4,
    },
    {
        id: 3,
        image: "https://www.course-api.com/images/people/person-3.jpeg",
        name: "peter smith",
        title: "product designer",
        quote: "Drinking vinegar polaroid street art echo park, actually semiotics next level butcher master cleanse hammock flexitarian ethical paleo.",
        rating: 4,
    },
    {
        id: 4,
        image: "https://www.course-api.com/images/people/person-2.jpeg",
        name: "susan andersen",
        title: "the boss",
        quote: "Marfa af yr 3 wolf moon kogi, readymade distillery asymmetrical seitan kale chips fingerstache cloud bread mustache twee messenger bag. ",
        rating: 4,
    },
    {
        id: 5,
        image: "https://www.course-api.com/images/people/person-1.jpeg",
        name: "maria ferguson",
        title: "office manager",
        quote: "Fingerstache umami squid, kinfolk subway tile selvage tumblr man braid viral kombucha gentrify fanny pack raclette pok pok mustache.",
        rating: 5,
    },
    {
        id: 6,
        image: "https://www.course-api.com/images/people/person-4.jpeg",
        name: "john doe",
        title: "regular guy",
        quote: "Gastropub sustainable tousled prism occupy. Viral XOXO roof party brunch actually, chambray listicle microdosing put a bird on it paleo subway tile squid umami.",
        rating: 3,
    },
    {
        id: 7,
        image: "https://www.course-api.com/images/people/person-3.jpeg",
        name: "peter smith",
        title: "product designer",
        quote: "Drinking vinegar polaroid street art echo park, actually semiotics next level butcher master cleanse hammock flexitarian ethical paleo.",
        rating: 5,
    },
    {
        id: 8,
        image: "https://www.course-api.com/images/people/person-2.jpeg",
        name: "susan andersen",
        title: "the boss",
        quote: "Marfa af yr 3 wolf moon kogi, readymade distillery asymmetrical seitan kale chips fingerstache cloud bread mustache twee messenger bag. ",
        rating: 5,
    },
];
